services:
  db:
    image: postgres:16
    container_name: minierp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: minierp
      POSTGRES_USER: minierp
      POSTGRES_PASSWORD: minierp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
